.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH /home/n4n5/Documents/github/coreutils/target/debug/build/coreutils-5760bf6c2a424d19/build-script-build 1  "/home/n4n5/Documents/github/coreutils/target/debug/build/coreutils-5760bf6c2a424d19/build-script-build 0.0.27" 
.SH NAME
/home/n4n5/Documents/github/coreutils/target/debug/build/coreutils\-5760bf6c2a424d19/build\-script\-build \- Display machine architecture
.SH SYNOPSIS
\fB/home/n4n5/Documents/github/coreutils/target/debug/build/coreutils\-5760bf6c2a424d19/build\-script\-build\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Display machine architecture
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH EXTRA
Determine architecture name for current machine.
.SH VERSION
v0.0.27
