.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_df 1  "uu_df 0.0.27" 
.SH NAME
uu_df \- Show information about the file system on which each FILE resides,
or all file systems by default.
.SH SYNOPSIS
\fBuu_df\fR [\fB\-\-help\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-B\fR|\fB\-\-block\-size\fR] [\fB\-\-total\fR] [\fB\-h\fR|\fB\-\-human\-readable\fR] [\fB\-H\fR|\fB\-\-si\fR] [\fB\-i\fR|\fB\-\-inodes\fR] [\fB\-k \fR] [\fB\-l\fR|\fB\-\-local\fR] [\fB\-\-no\-sync\fR] [\fB\-\-output\fR] [\fB\-P\fR|\fB\-\-portability\fR] [\fB\-\-sync\fR] [\fB\-t\fR|\fB\-\-type\fR] [\fB\-T\fR|\fB\-\-print\-type\fR] [\fB\-x\fR|\fB\-\-exclude\-type\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIpaths\fR] 
.SH DESCRIPTION
Show information about the file system on which each FILE resides,
or all file systems by default.
.SH OPTIONS
.TP
\fB\-\-help\fR
Print help information.
.TP
\fB\-a\fR, \fB\-\-all\fR
include dummy file systems
.TP
\fB\-B\fR, \fB\-\-block\-size\fR=\fISIZE\fR
scale sizes by SIZE before printing them; e.g.\*(Aq\-BM\*(Aq prints sizes in units of 1,048,576 bytes
.TP
\fB\-\-total\fR
produce a grand total
.TP
\fB\-h\fR, \fB\-\-human\-readable\fR
print sizes in human readable format (e.g., 1K 234M 2G)
.TP
\fB\-H\fR, \fB\-\-si\fR
likewise, but use powers of 1000 not 1024
.TP
\fB\-i\fR, \fB\-\-inodes\fR
list inode information instead of block usage
.TP
\fB\-k\fR
like \-\-block\-size=1K
.TP
\fB\-l\fR, \fB\-\-local\fR
limit listing to local file systems
.TP
\fB\-\-no\-sync\fR
do not invoke sync before getting usage info (default)
.TP
\fB\-\-output\fR=\fIFIELD_LIST\fR [default: source,size,used,avail,pcent,target]
use the output format defined by FIELD_LIST, or print all fields if FIELD_LIST is omitted.
.br

.br
[\fIpossible values: \fRsource, fstype, itotal, iused, iavail, ipcent, size, used, avail, pcent, file, target]
.TP
\fB\-P\fR, \fB\-\-portability\fR
use the POSIX output format
.TP
\fB\-\-sync\fR
invoke sync before getting usage info (non\-windows only)
.TP
\fB\-t\fR, \fB\-\-type\fR=\fITYPE\fR
limit listing to file systems of type TYPE
.TP
\fB\-T\fR, \fB\-\-print\-type\fR
print file system type
.TP
\fB\-x\fR, \fB\-\-exclude\-type\fR=\fITYPE\fR
limit listing to file systems not of type TYPE
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIpaths\fR]

.SH EXTRA
Display values are in units of the first available SIZE from \-\-block\-size,
and the DF_BLOCK_SIZE, BLOCK_SIZE and BLOCKSIZE environment variables.
Otherwise, units default to 1024 bytes (or 512 if POSIXLY_CORRECT is set).

SIZE is an integer and optional unit (example: 10M is 10*1024*1024).
Units are K, M, G, T, P, E, Z, Y (powers of 1024) or KB, MB,... (powers
of 1000).
.SH VERSION
v0.0.27
