.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_dirname 1  "uu_dirname 0.0.27" 
.SH NAME
uu_dirname \- Strip last component from file name
.SH SYNOPSIS
\fBuu_dirname\fR [\fB\-z\fR|\fB\-\-zero\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIdir\fR] 
.SH DESCRIPTION
Strip last component from file name
.SH OPTIONS
.TP
\fB\-z\fR, \fB\-\-zero\fR
separate output with NUL rather than newline
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH EXTRA
Output each NAME with its last non\-slash component and trailing slashes
removed; if NAME contains no /\*(Aqs, output \*(Aq.\*(Aq (meaning the current directory).
.SH VERSION
v0.0.27
