.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_factor 1  "uu_factor 0.0.27" 
.SH NAME
uu_factor \- Print the prime factors of the given NUMBER(s).
If none are specified, read from standard input.
.SH SYNOPSIS
\fBuu_factor\fR [\fB\-h\fR|\fB\-\-exponents\fR] [\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fINUMBER\fR] 
.SH DESCRIPTION
Print the prime factors of the given NUMBER(s).
If none are specified, read from standard input.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-exponents\fR
Print factors in the form p^e
.TP
\fB\-\-help\fR
Print help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fINUMBER\fR]

.SH VERSION
v0.0.27
