.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_hostid 1  "uu_hostid 0.0.27" 
.SH NAME
uu_hostid \- Print the numeric identifier (in hexadecimal) for the current host
.SH SYNOPSIS
\fBuu_hostid\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Print the numeric identifier (in hexadecimal) for the current host
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.27
