.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_logname 1  "uu_logname 0.0.27" 
.SH NAME
uu_logname \- Print user\*(Aqs login name
.SH SYNOPSIS
\fBuu_logname\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Print user\*(Aqs login name
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.27
