.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_mknod 1  "uu_mknod 0.0.27" 
.SH NAME
uu_mknod \- Create the special file NAME of the given TYPE.
.SH SYNOPSIS
\fBuu_mknod\fR [\fB\-m\fR|\fB\-\-mode\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fINAME\fR> <\fITYPE\fR> [\fIMAJOR\fR] [\fIMINOR\fR] 
.SH DESCRIPTION
Create the special file NAME of the given TYPE.
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-mode\fR=\fIMODE\fR
set file permission bits to MODE, not a=rw \- umask
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fINAME\fR>
name of the new file
.TP
<\fITYPE\fR>
type of the new file (b, c, u or p)
.TP
[\fIMAJOR\fR]
major file type
.TP
[\fIMINOR\fR]
minor file type
.SH EXTRA
Mandatory arguments to long options are mandatory for short options too.
\-m, \-\-mode=MODE    set file permission bits to MODE, not a=rw \- umask

Both MAJOR and MINOR must be specified when TYPE is b, c, or u, and they
must be omitted when TYPE is p.  If MAJOR or MINOR begins with 0x or 0X,
it is interpreted as hexadecimal; otherwise, if it begins with 0, as octal;
otherwise, as decimal.  TYPE may be:

* b      create a block (buffered) special file
* c, u   create a character (unbuffered) special file
* p      create a FIFO

NOTE: your shell may have its own version of mknod, which usually supersedes
the version described here.  Please refer to your shell\*(Aqs documentation
for details about the options it supports.
.SH VERSION
v0.0.27
