.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_tty 1  "uu_tty 0.0.27" 
.SH NAME
uu_tty \- Print the file name of the terminal connected to standard input.
.SH SYNOPSIS
\fBuu_tty\fR [\fB\-s\fR|\fB\-\-silent\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Print the file name of the terminal connected to standard input.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-silent\fR
print nothing, only return an exit status
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.27
