.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_users 1  "uu_users 0.0.27" 
.SH NAME
uu_users \- Print the user names of users currently logged in to the current host.
.SH SYNOPSIS
\fBuu_users\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIfiles\fR] 
.SH DESCRIPTION
Print the user names of users currently logged in to the current host.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIfiles\fR]

.SH VERSION
v0.0.27
