.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_unlink 1  "uu_unlink 0.0.27" 
.SH NAME
uu_unlink \- Unlink the file at `FILE`.
.SH SYNOPSIS
\fBuu_unlink\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Unlink the file at `FILE`.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.27
