.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_yes 1  "uu_yes 0.0.27" 
.SH NAME
uu_yes \- Repeatedly display a line with STRING (or \*(Aqy\*(Aq)
.SH SYNOPSIS
\fBuu_yes\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fISTRING\fR] 
.SH DESCRIPTION
Repeatedly display a line with STRING (or \*(Aqy\*(Aq)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fISTRING\fR]

.SH VERSION
v0.0.27
