[package]
name = "uu_nice"
description = "nice ~ (uutils) run PROGRAM with modified scheduling priority"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/nice"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
path = "src/nice.rs"
test = false
doctest = false

[target.'cfg(unix)'.dependencies]
clap = { workspace = true }
rustix = { workspace = true, features = ["process"] }
uucore = { workspace = true }
fluent = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "nice"
path = "src/main.rs"
required-features = ["uucore/default"]
