// This file is part of the uutils coreutils package.
//
// For the full copyright and license information, please view the LICENSE
// file that was distributed with this source code.
//
// spell-checker:ignore SIGSEGV

//! A collection of procedural macros for uutils.
#![deny(missing_docs)]

use proc_macro::TokenStream;
use quote::quote;

//## rust proc-macro background info
//* ref: <https://dev.to/naufraghi/procedural-macro-in-rust-101-k3f> @@ <http://archive.is/Vbr5e>
//* ref: [path construction from LitStr](https://oschwald.github.io/maxminddb-rust/syn/struct.LitStr.html) @@ <http://archive.is/8YDua>

fn alloc_error_exit_code(args: &str) -> Option<u8> {
    args.split(',').find_map(|arg| {
        let (name, value) = arg.split_once('=')?;
        if name.trim() != "alloc_error_exit_code" {
            return None;
        }

        let code = value.trim().parse::<u8>().unwrap_or_else(|_| {
            panic!("alloc_error_exit_code must be an integer between 1 and 255")
        });

        assert!(
            code != 0,
            "alloc_error_exit_code must be an integer between 1 and 255"
        );

        Some(code)
    })
}

/// A procedural macro to define the main function of a uutils binary.
///
/// This macro handles:
/// - SIGPIPE state capture at process startup (before Rust runtime overrides it)
/// - SIGPIPE restoration to default if parent didn't explicitly ignore it
/// - Disabling Rust signal handlers for proper core dumps
/// - Error handling and exit code management
/// - Per-utility allocation failure exit code configuration
///
/// The allocation failure exit code defaults to 1. Utilities that require a
/// different status can use `#[uucore::main(alloc_error_exit_code = 2)]`.
#[proc_macro_attribute]
pub fn main(args: TokenStream, stream: TokenStream) -> TokenStream {
    let stream = proc_macro2::TokenStream::from(stream);
    let args = args.to_string();
    // Some utils e.g. true does not require signals
    let signals = !args.split(',').any(|arg| arg.trim() == "no_signals");
    let alloc_error_exit_code = alloc_error_exit_code(&args);
    let alloc_error_config = if let Some(code) = alloc_error_exit_code {
        quote!(uucore::allocation::AllocErrorConfig::new(env!("CARGO_PKG_NAME"), #code))
    } else {
        quote!(uucore::allocation::AllocErrorConfig::default_for(env!(
            "CARGO_PKG_NAME"
        )))
    };

    let new = quote!(
        #[doc(hidden)]
        /// Allocation-failure policy generated by `uucore::main`.
        pub const UU_ALLOC_ERROR_CONFIG: uucore::allocation::AllocErrorConfig =
            #alloc_error_config;

        // Initialize SIGPIPE state capture at process startup (Unix only).
        // This must be at module level to set up the .init_array static that runs
        // before main() to capture whether SIGPIPE was ignored by the parent process.
        #[cfg(all(#signals, unix, not(any(target_os = "fuchsia", target_os = "haiku", target_os = "hurd"))))]
        uucore::init_startup_state_capture!();

        pub fn uumain(args: impl uucore::Args) -> i32 {
            #stream

            // Restore SIGPIPE to default if it wasn't explicitly ignored by parent.
            // The Rust runtime ignores SIGPIPE, but we need to respect the parent's
            // signal disposition for proper pipeline behavior (GNU compatibility).
            // needed even for true --version
            #[cfg(all(unix, not(any(target_os = "fuchsia", target_os = "haiku", target_os = "hurd"))))]
            if !uucore::signals::sigpipe_was_ignored() {
                let _ = uucore::signals::enable_pipe_errors();
            }

            // disable rust signal handlers (otherwise processes don't dump core after e.g. one SIGSEGV)
            #[cfg(all(#signals, unix))]
            uucore::disable_rust_signal_handlers().expect("Disabling rust signal handlers failed");
            let result = uumain(args);
            match result {
                Ok(()) => uucore::error::get_exit_code(),
                Err(e) => {
                    let s = format!("{e}");
                    if s != "" {
                        uucore::show_error!("{s}");
                    }
                    if e.usage() {
                        use std::io::{stderr, Write as _};
                        let _ = writeln!(stderr(),"Try '{} --help' for more information.", uucore::execution_phrase());
                    }
                    e.code()
                }
            }
        }
    );

    TokenStream::from(new)
}
