complete -c b3sum -s b -l binary -d 'read in binary mode'
complete -c b3sum -s c -l check -d 'read hashsums from the FILEs and check them'
complete -c b3sum -l tag -d 'create a BSD-style checksum'
complete -c b3sum -s t -l text -d 'read in text mode (default)'
complete -c b3sum -s q -l quiet -d 'don\'t print OK for each successfully verified file'
complete -c b3sum -s s -l status -d 'don\'t output anything, status code shows success'
complete -c b3sum -l strict -d 'exit non-zero for improperly formatted checksum lines'
complete -c b3sum -l ignore-missing -d 'don\'t fail or report status for missing files'
complete -c b3sum -s w -l warn -d 'warn about improperly formatted checksum lines'
complete -c b3sum -s z -l zero -d 'end each output line with NUL, not newline'
complete -c b3sum -l no-names -d 'Omits filenames in the output (option not present in GNU/Coreutils)'
complete -c b3sum -s h -l help -d 'Print help'
complete -c b3sum -s V -l version -d 'Print version'
