complete -c md5sum -s b -l binary -d 'read in binary mode'
complete -c md5sum -s c -l check -d 'read hashsums from the FILEs and check them'
complete -c md5sum -l tag -d 'create a BSD-style checksum'
complete -c md5sum -s t -l text -d 'read in text mode (default)'
complete -c md5sum -s q -l quiet -d 'don\'t print OK for each successfully verified file'
complete -c md5sum -s s -l status -d 'don\'t output anything, status code shows success'
complete -c md5sum -l strict -d 'exit non-zero for improperly formatted checksum lines'
complete -c md5sum -l ignore-missing -d 'don\'t fail or report status for missing files'
complete -c md5sum -s w -l warn -d 'warn about improperly formatted checksum lines'
complete -c md5sum -s z -l zero -d 'end each output line with NUL, not newline'
complete -c md5sum -s h -l help -d 'Print help'
complete -c md5sum -s V -l version -d 'Print version'
