complete -c uu_echo -s n -d 'do not output the trailing newline'
complete -c uu_echo -s e -d 'enable interpretation of backslash escapes'
complete -c uu_echo -s E -d 'disable interpretation of backslash escapes (default)'
complete -c uu_echo -s h -l help -d 'Print help'
complete -c uu_echo -s V -l version -d 'Print version'
