##
# Test runner
#
# @file
# @version 0.1

all: int unit

int:
	cargo test --features "dd" --no-default-features --manifest-path "../../../Cargo.toml"

unit:
	cargo test --manifest-path "./Cargo.toml"

# end
