[package]
name = "uu_chown"
description = "chown ~ (uutils) change the ownership of FILE"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/chown"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
path = "src/chown.rs"
doctest = false

[dependencies]
clap = { workspace = true }
fluent = { workspace = true }
uucore = { workspace = true, features = ["entries", "fs", "perms"] }

[target.'cfg(all(unix, not(any(target_os = "aix", target_os = "hurd", target_os = "redox"))))'.dependencies]
uucore = { workspace = true, features = ["safe-traversal"] }

[lints]
workspace = true

[[bin]]
name = "chown"
path = "src/main.rs"
