name: Android

# spell-checker:ignore (people) reactivecircus dtolnay
# spell-checker:ignore (shell/tools) TERMUX nextest udevadm pkill sccache
# spell-checker:ignore (misc) swiftshader playstore DATALOSS noaudio

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read # to fetch code (actions/checkout)

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TERMUX: v0.118.0
  COMMON_EMULATOR_OPTIONS: -no-metrics -no-window -noaudio -no-boot-anim -camera-back none -gpu off
  EMULATOR_DISK_SIZE: 6GB
  EMULATOR_HEAP_SIZE: 1024M
  EMULATOR_BOOT_TIMEOUT: 600
  EMULATOR_RAM_SIZE: 3072M
  EMULATOR_CORES: 4

jobs:
  test_android:
    name: Test builds
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        api-level: [28]
        target: [google_apis_playstore]
        arch: [x86_64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Collect information about runner
      if: always()
      continue-on-error: true
      run: |
        hostname
        uname -a
        free -mh
        df -Th
        cat /proc/cpuinfo
    - name: (Linux) create links from home to data partition
      if: ${{ runner.os == 'Linux' }}
      continue-on-error: true
      run: |
        ls -lah /mnt/
        cat /mnt/DATALOSS_WARNING_README.txt
        sudo mkdir /mnt/data
        sudo chmod a+rwx /mnt/data
        mkdir /mnt/data/.android && ln -s /mnt/data/.android ~/.android
        mkdir /mnt/data/work && ln -s /mnt/data/work ~/work
    - name: Enable KVM group perms (linux hardware acceleration)
      if: ${{ runner.os == 'Linux' }}
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - uses: actions/checkout@v7.0.1
      with:
        persist-credentials: false
    - name: Run sccache-cache
      id: sccache-setup
      uses: mozilla-actions/sccache-action@v0.0.11
      continue-on-error: true
    - name: Export sccache
      if: steps.sccache-setup.outcome == 'success'
      run: |
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-linux-android
    - name: Install cargo-nextest on host
      uses: taiki-e/install-action@cargo-nextest
    - name: Cross-compile coreutils and tests for Android
      run: |
        export ANDROID_NDK_ROOT=${ANDROID_NDK_LATEST_HOME:-$ANDROID_NDK_HOME}
        export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
        export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER=$TOOLCHAIN/bin/x86_64-linux-android28-clang
        export CARGO_TARGET_X86_64_LINUX_ANDROID_AR=$TOOLCHAIN/bin/llvm-ar
        export CC_x86_64_linux_android=$TOOLCHAIN/bin/x86_64-linux-android28-clang
        export CXX_x86_64_linux_android=$TOOLCHAIN/bin/x86_64-linux-android28-clang++
        export AR_x86_64_linux_android=$TOOLCHAIN/bin/llvm-ar

        mkdir -p target/nextest-target

        echo "=== Cross-compiling cargo-nextest for Android ==="
        cargo install cargo-nextest --target x86_64-linux-android --root target/nextest-target --locked

        echo "=== Cross-compiling coreutils & archiving tests with nextest ==="
        cargo nextest archive --target x86_64-linux-android --features feat_os_unix_android --archive-file target/test-archive.tar.zst
    - name: Run Android Emulator and Tests
      uses: reactivecircus/android-emulator-runner@v2.38.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: ${{ matrix.arch }}
        ram-size: ${{ env.EMULATOR_RAM_SIZE }}
        heap-size: ${{ env.EMULATOR_HEAP_SIZE }}
        disk-size: ${{ env.EMULATOR_DISK_SIZE }}
        cores: ${{ env.EMULATOR_CORES }}
        force-avd-creation: false
        emulator-options: ${{ env.COMMON_EMULATOR_OPTIONS }}
        emulator-boot-timeout: ${{ env.EMULATOR_BOOT_TIMEOUT }}
        script: |
          util/android-commands.sh init "${{ matrix.arch }}" "${{ matrix.api-level }}" "${{ env.TERMUX }}"
          util/android-commands.sh sync_tests target/test-archive.tar.zst target/nextest-target/bin/cargo-nextest
          util/android-commands.sh tests
    - name: archive any output (error screenshots)
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test_output_${{ matrix.arch }}_${{ matrix.api-level }}
        path: output
    - name: Collect information about runner resources
      if: always()
      continue-on-error: true
      run: |
        free -mh
        df -Th
