[package]
name = "uutests_procs"
description = "uutils ~ 'uutests' proc-macros"
repository = "https://github.com/uutils/coreutils/tree/main/tests/uutests_procs"
keywords = ["cross-platform", "proc-macros", "uutests", "uutils"]
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
proc-macro2.workspace = true
quote.workspace = true

[lints]
workspace = true
